### ISSUE TITLE
Dazza - Assigned Task of finding thumbnails for website

### ISSUE THREAD

**Issue by prhana** [MassachusettsLegalHackers/orgsetup#11]

**Comment by prhana** [comment]
1. API Dev Guide
2. Install a button
3. Embed video place holder

**Comment by dazzaji** [comment]
And... done!

![screen shot 2015-12-11 at 7 08 08 am](https://cloud.githubusercontent.com/assets/2357755/11743515/2c25222a-9fd6-11e5-8fad-a434d96c801c.png)
