### ISSUE TITLE
Dazza- two questions regarding the website

### ISSUE THREAD

**Issue by prhana** [MassachusettsLegalHackers/orgsetup#13]
The SOW states that:
1.) Needs nav to all major resources  
-link to Kantara: GitHub: https://github.com/KantaraInitiative/CISWG 
Wordpress Blog: which is already up there

Do you think that we need any links to the CISWG Kantara repo?

2.) Include a contact form using google forms for people to interact with the project 

We have not talked about this during our Hangout conversation, do you have any suggestions for creating it and if so, what do you think is the best destination for form submissions?

**Comment by dazzaji** [comment]
## Example google form (just use name and email)
- https://docs.google.com/a/civics.com/forms/d/1HBh_AF1H6szkHgX3O1QkLKu6iuBDFFRzo8RDdDCdfu4/viewform

In Google form maker name looks like this:

![screen shot 2015-12-11 at 1 54 39 am](https://cloud.githubusercontent.com/assets/2357755/11737788/c07030c2-9faa-11e5-9f42-03fd6c0ca975.png)

The email looks like this:

![screen shot 2015-12-11 at 1 54 31 am](https://cloud.githubusercontent.com/assets/2357755/11737798/ce7f86ea-9faa-11e5-83a7-4864f02e1dd1.png)

## Links to Kantara:
- Kantara: GitHub: https://github.com/KantaraInitiative/CISWG 
- Kantara Blog:http://blog.consentreceipt.org/
- Kantara Workgroup: https://kantarainitiative.org/confluence/display/infosharing/Home
