### ISSUE TITLE
Re: pointing subdomain api.Openconsent.net to Didars Heroku Server 

### ISSUE THREAD

**Issue by prhana** [MassachusettsLegalHackers/orgsetup#2]
Looks like we need for Didar to give DNS configuration details.

Dazza's response from Wednesday December 9 at 2:47am : "Awaiting response from @didaralam with the DNS details needed. If this item has been overtaken by events, then it is possible to use the alternative "default" URL provided for the herokuapp projects(eg: this site here https://boiling-caverns-7193.herokuapp.com). It may be easier to point the second level domain (ie: OpenConsent.net) and more difficult to point the third level domain (ie: "API.OpenConsent.net) to the herokuapp."

**Comment by dazzaji** [comment]
Agreed. This is also reflective of Marks response from a prior day.  Is it possible to get this resolved prior to the call?

**Comment by prhana** [comment]
Didar is unsure of how to do this, is Mark able to help?
