### ISSUE TITLE
Update Documentation Step #2

### ISSUE THREAD

**Issue by prhana** [MassachusettsLegalHackers/orgsetup#3]
Last time Dazza and I spoke, he asked me to add the following as an Issue. I am unclear of what it means, if it is still an open issue, or who is in charge of the task:

https://docs.google.com/document/d/1HQ7a_9r5hhXMocRfoK7H9LvqnJHFoLQmzcvYW9Y7Ws0/edit#heading=h.jnxyxkq6m7ku

Update code pointer from Kantara (current Kantara GitHub repo) to a Repo like this in the OpenConsent GitHub org: https://github.com/OpenConsent/CISWG

**Comment by dazzaji** [comment]
To clarify, the above means that the documentation of the API should be modified as follows:

Currently it states as step number  2. "Please Get the client and server side code onto your local machine’s working directory of your choice  from the Kantara GitHub Repository folder: CISWG https://github.com/KantaraInitiative/CISWG"

The pointer to code at "https://github.com/KantaraInitiative/CISWG" should be updated to point to The source code for the API in a repository that either open consent or legal hackers for the moment, and the code pointed to must be identical to the code described in the documentation and currently operating at the Hiroku server set up by Didar. 

Cantata is a terrific group however the best practice is to have the documentation refer to at least one single stable CodeBase that exists within a code repository that is not subject to change potentially without notice and based on unknowable future circumstances. In this case the project repositories are appropriate homes for both the documentation in the code in a single place that can be forked any number of times by any number of people or organizations who will always get the same working results.
