### ISSUE TITLE
Item 4 - Video to be created

### ISSUE THREAD

**Issue by prhana** [MassachusettsLegalHackers/orgsetup#5]

**Comment by prhana** [comment]
Storyboard: A consent receipt is... Here is an example: Show someone using the Mailchimp or (other form that we made) and getting a record of the consent they just gave. A do it yourself and learn more…

Add details about the receipt being encrypted. What do you say: Upon generating a unique consent receipt, the consent receipt is encrypted.

Mark to add here what is needed for video:

**Comment by dazzaji** [comment]
Project slides can be used as video and speaker notes as script:  https://docs.google.com/presentation/d/1l_z5ADFCM4C-aGgyZ7wQ8FoEZpN36QnH78l7YQ9oJwk/edit#slide=id.gdb01772f1_0_17

Caitlin is prepared to produce the video tomorrow before the final project review.  The thumb nail image on the third card (furthest from the left) can be replaced with an embed of the video from YouTube.
