### ISSUE TITLE
Mark to add Storyboard visual for encryption of consent receipt 

### ISSUE THREAD

**Issue by prhana** [MassachusettsLegalHackers/orgsetup#8]
Storyboard: 

Mark to add here what is needed for video:

**Comment by smartopian** [comment]
What you see and what you hear
1. an i agree button,
2. click it and get a receipt, 
3. show that it is a signed token
4. show that the data is encrypted so only the website and the user has can see it. (this i have to look into the visuals and audio for)

**Comment by dazzaji** [comment]
How does one show the token is signed?  You wrote "show that it is a signed token".  The question is: are you adding new requirements and functionality or was this already a capability that is implemented as part of  the existing form implemented as part of the API and also on the Kantara Workgroup site. 

If this is not scalability of the existing code then how does one do that?  How do you show that the API signed the token as a person that downloaded a file?

**Comment by smartopian** [comment]
I think we can just show the token in both the token data format (for Machine Readable) and the human readable format (which is the receipt once rendered)

**Comment by dazzaji** [comment]
I'm not really sure what you are suggesting, but it looks like Caitlin did a good job on the slide!

![screen shot 2015-12-11 at 7 11 44 am](https://cloud.githubusercontent.com/assets/2357755/11743559/79201c1a-9fd6-11e5-9c5f-245c80c9537c.png)

**Comment by dazzaji** [comment]
and that the site is done.

![screen shot 2015-12-11 at 7 08 08 am](https://cloud.githubusercontent.com/assets/2357755/11743571/948b210c-9fd6-11e5-9264-58de49eddafc.png)
