### ISSUE TITLE
Private Key - Danger

### ISSUE THREAD

**Issue by prhana** [MassachusettsLegalHackers/orgsetup#9]
We need to address the issue that there is a private key that is stemin from Kantara repo and now in the Consent Receipt code base

**Comment by smartopian** [comment]
About Key Danger
I found Some previous discussion on this topic. 

-- > 

Good afternoon! I have setup the mvcr app on heroku but ran into a little problem. The app is trying to access a file named "key.jwk" that most likely contains the key to sign the cr's. On heroku those kind of secret things (keys, credentials etc.) go into config vars and are then accessed from the app via the environment (ENV). So if we want to go ahead with heroku the code would need to be changed to retrieve the keys from environment variables. 

*_response *_
The key.jwks file can be generated at https://mkjwk.org/ - it's just a plain rsa key, copy the results of the "keypair" box into a file.  N

We didn't package this for heroku, though, so I'm not sure what it will take to get it going there. Hopefully the key is the only issue. This file obviously can't be checked into git, and I'm not sure how it would fit into an environment variable.
